"""alter is_admin field

Revision ID: ced64c8fdc24
Revises: 163523b872a7
Create Date: 2025-08-21 14:09:47.225606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced64c8fdc24'
down_revision: Union[str, Sequence[str], None] = '163523b872a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_admin_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin_user', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
